modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
showAsResourcePack=false

[[mods]]
    modId="inventoryactions"
    version="1.0.0"
    displayName="Inventory Actions"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/inventory-actions"
    #logoFile="logo.png"
    authors="HighFox"
    description='''
    Allows various interactions between blocks and items to be performed within the inventory.
    '''

[[dependencies.inventoryactions]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.inventoryactions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"