modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/High-Fox/InventoryActions/issues"
license="MIT License"

[[mods]]
    modId="inventoryactions"
    version="${file.jarVersion}"
    displayName="Inventory Actions"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/inventory-actions"
    logoFile="logo.png"
    authors="HighFox"
    description='''
    Allows various interactions between blocks and items to be performed within the inventory.
    '''

[[dependencies.inventoryactions]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.inventoryactions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"